### ISSUE TITLE
メイン画面（概要）

### ISSUE THREAD

**Issue by takagai2** [takagai2/RakutenRanking#1]
-  ヘッダー
    -  タイトル（後にランキング種別を表示）

-  リスト表示

-  フッター
    -  リスト表示、コレクション表示、ページ表示を選択するボタン

**Comment by takagai2** [comment]
色、アイコンの配置、大きさ等は参考画像に寄せて作成する形で良いですか？

**Comment by kaneshirc** [comment]
色はご自由に！
配置は参考画像に寄せる形で
大きさは作ってる上でいい感じに調整してください。

iOS標準に寄せるならこうです　というのがあれば提案ください。

**Comment by kaneshirc** [comment]
枠できてるのでclose
