### ISSUE TITLE
[親]お気に入り登録機能

### ISSUE THREAD

**Issue by takagai2** [takagai2/RakutenRanking#12]
~~-  Realmにお気に入り情報を保存~~
-  ランキングにお気に入りボタン実装

**Comment by sasagawanoriyuki** [comment]
情報の保存は #5 で対応するので、下記で良さそうです
* ランキングにお気に入りボタン実装
* `RankingManger` とプロトコルをつなぐ

**Comment by sasagawanoriyuki** [comment]
マージしましたのでクローズします
