### ISSUE TITLE
商品ページのハートアイコンに「F」という文字が入っている

### ISSUE THREAD

**Issue by sasagawanoriyuki** [takagai2/RakutenRanking#123]
商品ページのお気に入りのハートアイコンに白でFという文字があるようなので、そちらを消してください。
たぶん消し忘れかと思います。

**Comment by takagai2** [comment]
<img width="375" alt="default" src="https://user-images.githubusercontent.com/36285711/40900648-8c85b4da-6807-11e8-9660-c37d4c5a7b56.png">

**Comment by sasagawanoriyuki** [comment]
マージしましたのでクローズしますー
