### ISSUE TITLE
設定画面（概要）

### ISSUE THREAD

**Issue by takagai2** [takagai2/RakutenRanking#15]
-  アプリ起動時に表示されるランキング種別の変更
-  キャッシュクリアボタン（画像リソース）
-  お気に入りリセットボタン

**Comment by takagai2** [comment]
表示方法はモーダル/ポップアップ？/画面遷移...どんな感じになりますか？

**Comment by kaneshirc** [comment]
画面遷移にしましょう。

**Comment by sasagawanoriyuki** [comment]
マージしましたのでクローズします
