### ISSUE TITLE
ざっくりとした画面遷移＆テストデータ表示

### ISSUE THREAD

**Issue by kaneshirc** [takagai2/RakutenRanking#23]
refs #22

1. ざっくりとしたデザインで各画面を準備して画面遷移できるようにする。
2. mock作成（テストデータ[APIコールなどせずに固定値]）を返す処理を実装して、そちらのデータを画面で表示できるようにする

**Comment by takagai2** [comment]
こちらも今回のPRでマージされれば
`
mock -> リスト表示 -> アイテム詳細画面
`
までテストデータを渡して表示できるので完了。

**Comment by takagai2** [comment]
こちらもcloseよろしくお願いします。

**Comment by sasagawanoriyuki** [comment]
マージされているようなのでcloseしますー
