### ISSUE TITLE
API取得

### ISSUE THREAD

**Issue by takagai2** [takagai2/RakutenRanking#4]
-  API取得用クラス作成
-  API取得
-  HTTPクライアントはAFNetworkingを利用

**Comment by kaneshirc** [comment]
APIからのデータ取得処理は1つのサービスクラスにまとめること

**Comment by takagai2** [comment]
了解しました。

**Comment by sasagawanoriyuki** [comment]
分割するとしたら
* プロトコルクラスの作成
* APIのリクエスト処理
* レスポンス受取用のJsonObject作成とパース（リスト変換も含む）
