### ISSUE TITLE
ATS対応

### ISSUE THREAD

**Issue by choushi** [takagai2/RakutenRanking#42]
https://mushikago.com/i/?p=6150
https://dev.classmethod.jp/smartphone/iphone/ios-9-intro-ats/

`ATS を無効にする (非推奨)` の方法でHTTP通信を許可してあげる

**Comment by sasagawanoriyuki** [comment]
もしかするとATS対応要らないかもです。
リクエストURLが `https` なので。
`https://app.rakuten.co.jp/services/api/IchibaItem/Ranking/20170628?format=json&applicationId=57d2477d0f745c762f6e1068be018a78`

**Comment by takagai2** [comment]
現在アプリ内で使用する可能性のある全てのURLでSSL対応を確認しましたので、
こちらのissueは対応しない方向です。
（必要性が出てくる場合はその際に対応します。）

**Comment by takagai2** [comment]
closeお願いします。
