### ISSUE TITLE
[親]Realmクラスの実装

### ISSUE THREAD

**Issue by takagai2** [takagai2/RakutenRanking#5]
-  Realmの設定クラス

**Comment by sasagawanoriyuki** [comment]
分割するならば
* ライブラリのインポート
*  initializeの実装(https://realm.io/docs/swift/latest/)
* Entityクラスの実装
* プロトコルクラスの実装
* 実際の書き込みと読み出しの実装

**Comment by sasagawanoriyuki** [comment]
関連するissueが全てクローズされましたのでこちらもクローズします
