### ISSUE TITLE
ランキング画面（リスト表示）

### ISSUE THREAD

**Issue by takagai2** [takagai2/RakutenRanking#6]
-  メイン画面にてランキングをリスト表示させる

**Comment by takagai2** [comment]
ランキングの選択可能な種別は
-  総合
-  男女別総合（２パターン）
-  年齢別総合（５パターン）
-  男女別年齢別総合（１０パターン）
の計１８パターンという認識で合ってますか？

**Comment by kaneshirc** [comment]
こちら楽天APIの仕様を調べてください。

**Comment by takagai2** [comment]
一つのランキング種別のみのリスト表示は実装済み。
絞り込みによって表示されるランキング種別の変更は未実装です。

**Comment by kaneshirc** [comment]
>絞り込みによって表示されるランキング種別の変更は未実装です。

こちらは楽天APIを実際に組み込んでからになるのでcloseしますね。
